FROM maven:3.6.3-jdk-8-slim AS builder

COPY . .
RUN mvn package

FROM paperspigot:1.8.8

# TODO: pull maps from cloud storage

COPY maps/runs /opt/spigot/plugins/Flash/maps
COPY maps/spawns/spawn/ /opt/spigot/spawn
COPY config/* /opt/spigot/
COPY --from=builder target/flash.jar /opt/spigot/plugins
