FROM openjdk:8-alpine AS builder

WORKDIR /minecraft
ADD https://papermc.io/api/v1/paper/1.8.8/latest/download paper.jar
RUN java -jar paper.jar

FROM openjdk:8-alpine

EXPOSE 25565
WORKDIR /opt/spigot
COPY --from=builder /minecraft/cache/patched*.jar /opt/spigot/spigot.jar

CMD java -jar -Dcom.mojang.eula.agree=true spigot.jar
